#!/bin/bash

# Script to help fix mailcow authentication issue

echo "=================================="
echo "Mailcow Email Authentication Fix"
echo "=================================="
echo ""
echo "The email authentication is failing because the password in .env doesn't match"
echo "the password set in mailcow for the no-reply@wavemax.promo mailbox."
echo ""
echo "Current Configuration:"
echo "- Email: no-reply@wavemax.promo"
echo "- Password in .env: zsUoLLT4pcNIznRbYRWK"
echo ""
echo "To fix this issue, you need to:"
echo ""
echo "1. Access the Mailcow admin panel:"
echo "   https://mail.wavemax.promo:8443"
echo ""
echo "2. Login with admin credentials"
echo ""
echo "3. Go to 'Configuration' → 'Mailboxes'"
echo ""
echo "4. Find 'no-reply@wavemax.promo' and click edit (pencil icon)"
echo ""
echo "5. Update the password to: zsUoLLT4pcNIznRbYRWK"
echo ""
echo "6. Save the changes"
echo ""
echo "7. Wait 30 seconds for changes to propagate"
echo ""
echo "8. Test the email configuration:"
echo "   node scripts/test-mailcow-email.js"
echo ""
echo "Alternative: If the mailbox doesn't exist, create it with:"
echo "- Username: no-reply"
echo "- Domain: wavemax.promo"
echo "- Password: zsUoLLT4pcNIznRbYRWK"
echo "- Full name: No Reply"
echo ""
echo "=================================="